name:                markdown-preview-haskell
version:             0.1.0.0
github:              "misaelaguayo/markdown-preview-haskell"
license:             BSD3
author:              "Misael Aguayo"
maintainer:          "aguayo.misael@gmail.com"
copyright:           "2023 Misael Aguayo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/misaelaguayo/markdown-preview-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- temporary
- process
- split
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  markdown-preview-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markdown-preview-haskell

tests:
  markdown-preview-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markdown-preview-haskell
